version: 0.2

phases:
  install:
    commands:
      - npm i npm@latest -g
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      # Clear the deployment bucket to make sure all files are current
      - aws s3 rm --recursive "s3://${OUTPUT_BUCKET}/"
artifacts:
  files:
    - "**/*"
  base-directory: dist
